services:
  inventrack-backend:
    image: node:22.13.0-slim
    container_name: inventrack-backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4010:4010"
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: development
      PORT: 4010
    command: >
      sh -c "apt-get update -qq && apt-get install -y --no-install-recommends python3 make g++ openssl &&
             npm install &&
             npx prisma generate &&
             npx prisma db push --skip-generate &&
             npm run build &&
             node dist/server.js"
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
